@startuml
skinparam Linetype ortho

skinparam Swimlane {
  TitleFontColor black
  TitleBackgroundColor #C2DEF8
  BorderColor black
  BorderThickness 1
}

skinparam Activity {
  BorderColor #A8D0F6
  BackgroundColor #C2DEF8
  DiamondBackgroundColor #FAE1B8
  DiamondFontColor black
  DiamondBorderColor #F7D499
}

title Ablauf eines Tests mit Franklyn

|#c4c9cd|Examiner|
|#dee4e8|Examinee|
|#daf0fe|Client|


|Examiner|
start
    :Meldet sich mit 
    \n WebUntis-Daten an;
    :Erstellt PIN;
    |Examinee|
    repeat
    :Meldet sich mit PIN im Client an;
    |Client|
    repeat while (PIN gültig?)
    -> Ja;
    split
        :Gibt Namen ein;
        |Examinee|
        repeat
        :Schreibt Code;
        if (Stellt Frage?) then (Ja)
            |Examiner|
            :Öffnet Screenshots des Schülers;
            :Nimmt diese zur Kenntnis und probiert, 
            dem Schüler bestmöglich zu helfen;
        endif
        |Examinee|
        :Kompilieren;
        repeat while (Test abgegeben?)
        stop
    split again
        |Client|
        repeat
        :Erstellt Screenshot;
        :Sendet Screenshot an Server;
        repeat while (Franklyn geschlossen?)
        -> Ja;
        stop
    end split
@enduml