apiVersion: apps/v1
kind: Deployment
metadata:
  name: franklyn-db-deployment
  namespace: student-t-stuetz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: franklyndatabase
  template:
    metadata:
      labels:
        app: franklyndatabase
    spec:
      containers:
        - name: franklyndatabase
          image: postgres
          ports:
            - containerPort: 5432
              name: "postgres"
          env:
            - name: POSTGRES_DB
              value: db
            - name: POSTGRES_USER
              value: app
            - name: POSTGRES_PASSWORD
              value: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: franklyn-backend-deployment
  namespace: student-t-stuetz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: franklyn-backend
  template:
    metadata:
      labels:
        app: franklyn-backend
    spec:
      volumes:
        - name: shared-data
          emptyDir: { }
      containers:
        - name: franklyn-imageserver
          image: nginx
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/nginx/html
          ports:
            - containerPort: 80
        - name: franklyn-backend
          image: ghcr.io/htl-leonding-project/franklyn-quarkus-backend
          env:
            - name: PATHOFSCREENSHOT
              value: /t.stuetz/franklyn3/tmp/file-upload/exams
            - name: CURRENT_HOST
              value: https://student.cloud.htl-leonding.ac.at/
            - name: CURRENT_ROOT_DIRECTORY
              value: Desktop/file-upload/exams
            - name: FFMPEG_PATH
              value: /usr/bin/ffmpeg
          volumeMounts:
            - name: shared-data
              mountPath: /t.stuetz/franklyn/tmp/file-upload/exams
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: franklyn-frontend-deployment
  namespace: student-t-stuetz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: franklyn-frontend
  template:
    metadata:
      labels:
        app: franklyn-frontend
    spec:
      containers:
        - name: franklyn-frontend
          image: ghcr.io/htl-leonding-project/franklyn-quarkus-frontend
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: franklyn-backend-svc
  namespace: student-t-stuetz
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: franklyn-backend
---
apiVersion: v1
kind: Service
metadata:
  name: franklyn-imageserver-svc
  namespace: student-t-stuetz
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: franklyn-backend
---
apiVersion: v1
kind: Service
metadata:
  name: franklyn-frontend-svc
  namespace: student-t-stuetz
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: franklyn-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: franklyn-database-svc
  namespace: student-t-stuetz
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: franklyndatabase
  selector:
    app: franklyndatabase
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: franklyn-backend-ingress
  namespace: student-t-stuetz
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: student.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /t.stuetz/franklyn/api(/|$)(.*)$
            pathType: Prefix
            backend:
              service:
                name: franklyn-backend-svc
                port:
                  number: 80
          - path: /t.stuetz/franklyn/tmp/file-upload/exams(/|$)(.*)$
            pathType: Prefix
            backend:
              service:
                name: franklyn-imageserver-svc
                port:
                  number: 80
          - path: /t.stuetz/franklyn(/|$)(.*)$
            pathType: Prefix
            backend:
              service:
                name: franklyn-frontend-svc
                port:
                  number: 80
