apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: franklyn-pvc
  namespace: default
spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Mi
    storageClassName: standard
