apiVersion: v1
kind: Service
metadata:
  labels:
    app: franklyn-db
  name: franklyn-db-service
  namespace: default
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: franklyn-db-service
  selector:
    app: franklyn-db
  sessionAffinity: None
  type: LoadBalancer

