@startuml
'https://plantuml.com/class-diagram

class Exam{
    pin: String
    title: String
    ongoing: Boolean
    schoolClasses: List<SchoolClass>
    date: LocalDate
    startTime: LocalDateTime
    endTime: LocalDateTime
}

class Examinee{
    firstName: String
    lastName: String
    exam: Exam
}


class ExamineeDetails{
    examinee: Examinee
    isOnline: Boolean
    lastOnline: LocalDateTime
}

class Examiner{
    userName: String
    firstName: String
    lastName: String
    isAdmin: Boolean
    exam: Exam
}

class Screenshot{
    timestamp: Timestamp
    runningNo: Number
    examinee: Examinee
    resolution: Resolution
    compression: Number
    isCompressed: IsCompressed
    pathOfScreenshot: String
}

enum IsCompressed{
    NOT_COMPRESSED
    CURRENTLY_COMPRESSED
    COMPRESSED
}

class requestSummary{
    duration: Number
    endpoint: String (?)
    date: LocalDate
}

class SchoolClass{
    title: String
    year: String
}

class config{
    configVersion: Number
    examinerLoginType: String
    storage: ?
    storageUtilizationCheck: ?
    heartbeat: ?
    examsToDelete:
    pinLength: Number
    webUntis:
    endOfSchoolYear: String
    maintenance: boolean
}

enum Resolution{
    HD
    NATIVE
    FHD
}

Examinee "*" --> "1" Exam
Examiner "*" --> "1" Exam
Examinee "1" <-- "*" Screenshot
ExamineeDetails "*" --> "1" Examinee
SchoolClass "*" <-- "1" Exam

@enduml