@startwbs
* Franklyn-Quarkus-Backend
** Sprint 01
***[#green] Screenshots des Bildschirms machen
***[#green] Screenshots abschicken
***[#green] Screenshots empfangen
** Sprint 02
***[#green] Testen des Backends mit gattling
***[#green] Entitäten testen
***[#green] Generieren der PINs
** Sprint 03
***[#green] Endpoints erstellen
****[#green] Examinee
*****[#green] GET
*****[#green] PUT
*****[#green] DELETE
****[#green] Examiner
*****[#green] GET
*****[#green] DELETE
*****[#green] POST
****[#green] Exam
*****[#green] GET
*****[#green] PUT
*****[#green] DELETE
*****[#green] POST
****[#green] SchoolClass
*****[#green] GET
*****[#green] DELETE
*****[#green] POST
****[#green] Screenshot
*****[#green] GET
*****[#green] POST
***[#red] Endpoints testen
** Sprint 04
***[#red] WebUntis-Authentifizierung
***[#red] Testen mit Frontend von Franklyn2
** Sprint 05
***[#red] Deployen
@endwbs