@startwbs
* Franklyn-Quarkus
** Sprint 01
***[#green] Screenshots des Bildschirms machen
***[#green] Screenshots abschicken
***[#green] Screenshots empfangen
** Sprint 02
***[#green] testen des Backends mit gattling
***[#green] Entitäten testen
***[#green] generieren der PINs
** Sprint 03
***[#yellow] Endpoints erstellen
****[#green] Examinee
*****[#green] GET
*****[#green] PUT
*****[#green] DELETE
****[#green] Examiner
*****[#green] GET
*****[#green] DELETE
*****[#green] POST
****[#yellow] Exam
*****[#green] GET
*****[#yellow] PUT
*****[#green] DELETE
*****[#skyblue] POST
****[#green] SchoolClass
*****[#green] GET
*****[#green] DELETE
*****[#green] POST
****[#yellow] Screenshot
*****[#green] GET
*****[#yellow] POST
***[#red] Endpoints testen
** Sprint 04
***[#red] WebUntis authentifizierung
***[#red] testen mit Frontend von Franklyn2
** Sprint 05
***[#red] deployen
@endwbs