@startwbs
* Franklyn-Quarkus
** Sprint 01
***[#green] Screenshots des Bildschirms machen
***[#green] Screenshots abschicken
***[#green] Screenshots empfangen
** Sprint 02
***[#green] testen des Backends mit gattling
***[#red] Entitäten testen
***[#green] generieren der PINs
** Sprint 03
***[#yellow] Endpoints erstellen
****[#green] Examinee
*****[#green] GET
*****[#green] PUT
*****[#green] DELETE
****[#yellow] Examiner
*****[#green] GET
*****[#red] DELETE
*****[#red] POST
****[#red] Exam
*****[#green] GET
*****[#red] PUT
*****[#red] DELETE
*****[#red] POST
****[#red] SchoolClass
*****[#green] GET
*****[#red] PUT
*****[#red] DELETE
*****[#red] POST
****[#green] Screenshot
*****[#green] GET
*****[#red] PUT
*****[#red] DELETE
*****[#red] POST
***[#red] Endpoints testen
***[#green] generieren der PINs
** Sprint 04
***[#red] testen mit Frontend von Franklyn2
***[#red] deployen
@endwbs