@startuml
@startwbs
* Franklyn-Quarkus
** Sprint 01
***[#green] Screenshots des Bildschirms machen
***[#green] Screenshots abschicken
***[#green] Screenshots empfangen
** Sprint 02
***[#green] testen des Backends mit gattling
***[#red] Entitäten testen
***[#green] generieren der PINs
***[#green] Datenbank erstellen
** Sprint 03
***[#yellow] Endpoints erstellen
****[#green] GET
****[#yellow] POST
****[#yellow] PUT
****[#yellow] DELETE
***[#red] Endpoints testen
** Sprint 04
***[#red] WebUntis authentifizierung
***[#red] Endpoints auf Franklyn2 "zuschneiden"
** Sprint 05
***[#red] testen mit Frontend von Franklyn2
***[#red] deployen
@endwbs
@enduml