@startuml

skinparam linetype polyline
skinparam databaseBackgroundColor Aqua

package backend{
    frame "quarkus-backend"
}

package client{
    frame "quarkus-client"
}

package frontend{

    frame "Angular"
}

package "DB" {
    database "Postgres"
 }

DB -r- backend
backend -d- frontend : http
backend -u- client : http

@enduml