@startuml

:Student: as student
:Teacher: as teacher

rectangle "Franklyn" {
    rectangle Client {
        usecase "Sends screenshots" as uc_sendsScreenshots
    }
    rectangle Examiner {
            usecase "Creates virtual classroom" as uc_createLobby
            usecase "Observes desktops of all participants" as uc_seeScreenshots
        }
}

student -- uc_sendsScreenshots
student -- uc_raiseHand
teacher -- uc_createLobby
teacher -- uc_seeScreenshots
@enduml