logLevel = "DEBUG"

# defaultEntryPoints must be at the top
# because it should not be in any table below
defaultEntryPoints = ["http", "https"]

# Entrypoints, http and https
[entryPoints]

# http should be redirected to https
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"

# https is the default
[entryPoints.https]
address = ":443"
[entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "franklyn2.htl-leonding.ac.at"
watch = true
exposedByDefault = false

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
email = "groupfranklyn@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
acmeLogging = true

# Enable web configuration backend
[api]
entrypoint = "api"