= Presentation
Melcher Tamara und Tran Michael
31.01.2022
:toc:
:icons: font

== Was ist Franklyn?
Franklyn wurde bereits von Schülern programmiert.

Franklyn ist eine Applikation, welche Schülern eine der Berufswelt entsprechende Arbeitsumgebung während Leistungsfeststellungen bietet.

Lehrkräfte bekommen die Möglichkeit, Testsitzungen zu erstellen. Schüler können sich zu einer Sitzung mit einem PIN und dem Vor- und Nachnamen anmelden.
Der Schülerclient sendet dabei in einem regelmäßigen Intervall Screenshots, welche sich die Lehrkraft ansehen können.
Für die Ansicht der Screenshots wird noch das Patroulierintervall angeboten, welches einem ermöglicht, automatisch durch die Screenshots der Schüler und Schülerinnen zu iterieren.

== Problemstellung
Franklyn2 wurde mit Node.js geschrieben.

Da sich bei Node.js die Libraries ständig ändert, muss ständig upgedated werden, um den Code funktionstüchtig zu halten.

== Use Case Diagram

[plantuml]
----
include::plantuml/ucd.puml[]
----

== Datenmodell

[plantuml]
----
include::plantuml/classDiagram.puml[]
----

== Systemarchitektur

[plantuml]
----
include::plantuml/system-architecture.puml[]
----

== Sachbestandsbericht

[plantuml]
----
include::plantuml/sachstandsbericht.puml[]
----


== Unsere Aufgaben
.Aufgaben
|===
|Aufgabe |Status

|Screenshots every 5 secs
|done

|Upload Image
|done

|Download Image
|Done

|Datenmodell
|In Progess

|MOM
|up-to-date

|Qute - Student Login
|In progress

|Datenmodell
|In progress

|===

== Was noch kommt

* Datenmodellbesprechung mit Prof. Stütz
* Login für Schüler
* Tests
* Lehrerfrontend

