POST https://mese.webuntis.com/WebUntis/jsonrpc.do?school=htbla linz leonding
Content-Type: application/json

{
"id":"OWNID",
"method":"authenticate",
"params":{"user":"OWNUSER", "password":"OWNPASSWORD", "client":"CLIENT"},
"jsonrpc":"2.0"
}


####

POST  https://mese.webuntis.com/WebUntis/jsonrpc.do
Content-Type: application/json

{
  "id": "OWNID",
  "method": "getTeachers",
  "params": "{}",
  "jsonrpc": "2.0"
}

###

POST http://localhost:8080/webuntis/authenticate
Content-Type: application/json

{
  "id":"OWNID",
  "method":"authenticate",
  "params":{"user":"OWNUSER", "password":"OWNPASSWORD", "client":"CLIENT"},
  "jsonrpc":"2.0"
}

###

POST http://localhost:8080/webuntis/getteachers
Content-Type: application/json

{
  "id": "OWNID",
  "method": "getTeachers",
  "params": "{}",
  "jsonrpc": "2.0"
}