== Meeting 2022-09-22

=== Aktuell vorhanden:

- Beinahe die gesamte Dokumentation wurde überarbeitet und erneuert.
- Dabei wurden auch die vererbten Dateien bzw. Skripten auf den stand des link:https://github.com/htl-leonding-college/asciidoctor-convert-template[asciidoctor-convert-template] gebracht.
- Eine Adoc-Slides Presentation wurde erstellt um das Projekt bestmöglichst vorstellen zu können.
- Die letzte Version des Programms ist als `.jar` in den GitHub-Releases aufzufinden.


==== Planung:

.bis zum Herbst
plantuml::../plantuml/todoGantt-alpha.puml[]

.bis Neujahr
plantuml::../plantuml/todoGantt-beta.puml[]

.im kommenden Jahr
plantuml::../plantuml/todoGantt-final.puml[]


=== Bugs, Probleme und Fragen:

==== Bugs:
- Screenshots laufen nicht auf allen Betriebssystemen einwandfrei

==== Fragen:
- Ist im Schulnetzwerk der direkte zugriff auf einen anderen PC möglich? (WS kommunikation mit Instructor, Streaming-Server)


=== Besprochene Themen:
- anstatt "Bilder" soll der Begriff "Screenshots" verwendet werden (Folie bearbeiten)
- Schüler und Lehrer sollen nicht genannt werden. -> allgemeiner!
** Instructor and Student
- Folie "Aufbau": Gleich Diagramm zeigen (Marketingdiagramm)
- Backroundimage von PC-Raum für die Präsentation, wo Studenten sitzen und arbeiten (Fotos in Action)


=== Ziele:

*bis xx.xx.202x:*

Was machen wir bis zum Ende des Jahres?
Übersichtlichen informative 
