@startuml
skinparam Linetype ortho
skinparam classFontSize 30


skinparam Swimlane {
  TitleFontColor black
  TitleBackgroundColor #C2DEF8
  BorderColor black
  BorderThickness 1
}

skinparam Activity {
  BorderColor #A8D0F6
  BackgroundColor #C2DEF8
  DiamondBackgroundColor #FAE1B8
  DiamondFontColor black
  DiamondBorderColor #F7D499
}

title Ablauf

|#daf0fe|Powerpoint|
|#dee4e8|Salesperson|
|#c4c9cd|Backend|
|#dee4e8|Recipient|
|#daf0fe|WebViewer|


|Salesperson|
start
split
    |Salesperson|
    :Opens Analytics in Powerpoint;
    |Powerpoint|
    :Requests Analytics;
    :Shows Analytics;
    stop

split again
    |Salesperson|
    :Sends Präsentation;
    |Powerpoint|
    :Requests sending E-Mails;
    |Backend|
    :Sends E-Mail;
    |Recipient|
    :Receives Mail;
    :Opens Link;
    |WebViewer|
   :Requests Presentation;
   split
       :Requests sending SMS;
       |Backend|
       :Sends SMS to Salesperson;
       |Salesperson|
       :Receives SMS;
       stop
   split again
       |WebViewer|
       repeat
      :Sends TrackingInfo Post;
      |Recipient|
      :Changes Slide/Changes Tab;
      |WebViewer|
      :Sends TrackingInfo Put;
      repeat while (Browser closed?)
      -> Yes;
      stop
    end split
@enduml