@startuml

skinparam linetype polyline
skinparam databaseBackgroundColor Aqua

package backend{
    frame "quarkus-backend"
}

package frontend{

    frame "angular"
}

package "DB" {
    database "postgres"
}

DB -r- backend
backend -d- frontend : http
frontend -- backend : http

@enduml