apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-02-15T10:31:30Z"
  generation: 1
  labels:
    app: franklyn-frontend
  name: franklyn-frontend
  resourceVersion: "21273"
  uid: cfaabafb-58d7-40ff-9dd5-099f06348457
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: franklyn-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: franklyn-frontend
    spec:
      containers:
        - env:
            - name: NEXT_PUBLIC_API_SERVER
              value: http://franklyn-application-server:8080
            - name: NEXT_PUBLIC_API_STREAMING_SERVER
              value: http://franklyn-streaming-server:8082
            - name: NEXT_PUBLIC_BASE_PATH
              value: /it190204/hahaha

          image: ghcr.io/htl-leonding-project/franklyn-frontend-image:latest
          imagePullPolicy: Always
          name: franklyn-frontend-image
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2024-02-15T10:31:30Z"
    lastUpdateTime: "2024-02-15T10:31:30Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2024-02-15T10:31:30Z"
    lastUpdateTime: "2024-02-15T10:31:30Z"
    message: ReplicaSet "franklyn-frontend-5687d99d89" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
