apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-01-25T10:35:06Z"
  generation: 1
  labels:
    app: franklyn-streaming-server
  name: franklyn-streaming-server
  resourceVersion: "15980"
  uid: 1270c42f-a231-4f22-b4e9-68cf996d7be7
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: franklyn-streaming-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: franklyn-streaming-server
    spec:
      containers:
      - image: ghcr.io/htl-leonding-project/franklyn-streaming-server-image:latest
        imagePullPolicy: Always
        name: franklyn-streaming-server-image
        ports:
        - containerPort: 8082
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-01-25T10:35:29Z"
    lastUpdateTime: "2024-01-25T10:35:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-01-25T10:35:06Z"
    lastUpdateTime: "2024-01-25T10:35:29Z"
    message: ReplicaSet "franklyn-streaming-server-586dffd4bd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
