= Frame Management
Franklyn 3 Dev-Team
2023/24: franklyn-quarkus
ifndef::imagesdir[:imagesdir: images]
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left


== Verwendete Technologien

- Java
- Quarkus Client
- OpenCV



== Grundsätzlich unterscheiden wir zwischen:

- Live Bilder
- Stream Bilder
- Alpha Frames
- Beta Frames

== Alpha-Frames:

Alpha-Frames sind reine Screenshots, die auf dem Schüler-Client gespeichert werden. +
Sie werden später bei der Differenzenrechnung verwendet.

== Beta-Frames:
Beta-Frames sind Screenshots, die mit den Alpha Frames verglichen werden. Die Unterschiede werden in ein File (.png) kopiert und auf dem Schüler-Client gespeichert.

== Live Bilder:

Live Bilder sind reine Screenshots, die zum Instructor Client während des Tests geschickt werden.


== Video Frames:

Am Ende müssen die Alpha- und die Beta-Frames zusammengelegt werden. +
Die zusammengelegten Frames werden später in der Erstellung von .mp4s verwendet.



== Wie werden die Differenzen gerechnet


- Am Anfang wird ein Screenshot aufgenommen, welcher als Alpha Frame bezeichnet wird.

- Die nächsten Screenshots werden mit diesem Alpha-Frame verglichen. Die Pixel von den Bildern werden miteinander verglichen. Für genauere Ergebnisse werden die Bilder in Graustufen umgewandelt.

- Die Differenzen werden auf einer Bitmap (Matrix oder Maske) gezeichnet.

- Die Masken werden wieder in das RGB Farbformat umgewandelt und auf der Festplatte von dem Schüler-Client gespeichert.

NOTE: Wenn der Prozentsatz der Differenzen über 30% liegt, wird der Alpha-Frame aktualisiert



== Wie werden die Alpha- und Beta-Frames zusammengelegt

- Das Programm ruft die letzten Alpha- und Beta-Frames ab.
- Eine leere Matrix wird erstellt.
- Die farbigen Pixel des Beta-Frames werden in die Matrix gezeichnet.
- Der Alpha-Frame wird in die Maske kopiert. Bereits vorhandene farbige Pixel in der Matrix bleiben unverändert. Es werden lediglich transparente Pixel durch farbige ersetzt.
- Die Matrix wird in eine Datei umgewandelt und auf der Festplatte des Servers gespeichert.

