name: Build
on:
  push:
    branches: [main]

jobs:
  building-slides:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: quirinecker/asciidoctor-convert-action@1.0
          with:
            slides: true
            inputPath: input
            outputPath: output