name: Build
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: build-slides
        uses: quirinecker/asciidoctor-convert-action@1.0
        with:
          slides: true
          inputPath: input
          outputPath: output